{% set name = "decopatch" %}
{% set version = "1.4.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/decopatch-{{ version }}.tar.gz
  sha256: b5882c8cf0d5b01d218b4e04f6762d07b3287420ea509706f59971c3d6fec56f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
    - setuptools_scm
  run:
    - makefun >=1.5.0
    - python >=3.5

test:
  imports:
    - decopatch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smarie/python-decopatch
  summary: Create decorators easily in python.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    Because of a tiny oddity in the python language, writing decorators without
    help can be a pain because you have to handle the no-parenthesis usage
    explicitly. `decopatch` provides a simple way to solve this issue so that
    writing decorators is simple and straightforward.
  doc_url: https://smarie.github.io/python-decopatch
  dev_url: https://github.com/smarie/python-decopatch

extra:
  recipe-maintainers:
    - smarie
